name: CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Prepare pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Install dependencies
        run: |
          echo "::group::Install dependencies"
          cd frontend
          pnpm install --frozen-lockfile
          echo "::endgroup::"

      - name: Lint
        run: |
          echo "::group::Lint"
          cd frontend
          pnpm lint
          echo "::endgroup::"

      - name: Test
        run: |
          echo "::group::Test"
          cd frontend
          pnpm test
          echo "::endgroup::"

      - name: Build
        run: |
          echo "::group::Build"
          cd frontend
          pnpm build
          echo "::endgroup::"
